### ISSUE TITLE
cant add the bot

### ISSUE THREAD

**Issue by SpreeHertz** [DjDeveloperr/ActivitiesBot#5]
Please verify the bot so I can add it to more servers.

**Comment by DjDeveloperr** [comment]
Bot had Suspicious growth error for a while now, just checked its not there so I'll be applying for verification today.

**Comment by DjDeveloperr** [comment]
![image](https://user-images.githubusercontent.com/43033058/114996306-54e0f000-9ebc-11eb-9cf6-d911d9eac4fc.png)

**Comment by DjDeveloperr** [comment]
Bot is now verified 🎉
