### ISSUE TITLE
Deno Not Authorized

### ISSUE THREAD

**Issue by ghost** [DjDeveloperr/ActivitiesBot#7]
![image](https://user-images.githubusercontent.com/73678945/149612854-e4a1235d-d94b-45f4-a05b-ece6c00afe3f.png)

bro i cant deploy the bots pls help

**Comment by DjDeveloperr** [comment]
That's intended, since the web server it creates is only accessible to Discord with correctly signed data. Just add the URL as Interactions Endpoint in Developer Portal.

**Comment by MJGaming1532** [comment]
still not work

**Comment by ghost** [comment]
still same

**Comment by DjDeveloperr** [comment]
What does not work? Can you give more info?

**Comment by ghost** [comment]
I've entered the endpoint into the discord developer portal but it's still Not Authorize
and I have also tried entering the redirect url too
but everything is still the same and error
with the words Not Authorized

**Comment by DjDeveloperr** [comment]
You don't have to open the site at all, it will always show that... just invite & use the bot in server now.

**Comment by MJGaming1532** [comment]
I've invited the bot but it's still offline

**Comment by ghost** [comment]
fixed!
I just changed a bit in the mod.ts file section
also thanks for help :)
